### ISSUE TITLE
Add Python Flask instructions

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/slate_apm_help#22]
https://github.com/scoutapp/scout_apm_python/blob/master/src/scout_apm/flask/__init__.py

**Comment by itsderek23** [comment]
@cschneid - mind sharing:

* A gist of the Flask install process, similar to [this](http://localhost:4567/#python-install).
* The earliest supported Flask version

**Comment by dlanderson** [comment]
https://docs.scoutapm.com/#flask
