### ISSUE TITLE
Mention generic GraphQL instructions in docs

### ISSUE THREAD

**Issue by coopr** [scoutapp/slate_apm_help#29]
Add this tip to our docs https://scout-community.slack.com/archives/GG6KNTK7Z/p1550040604005900 (this thread may not be publicly accessible) so that folks searching our docs for `GraphQL` find something more generally helpful than what we have there now

**Comment by cschneid** [comment]
- Copying here to avoid losing it.



Hi @Manikandan,
Regarding graphql, I actually got confused with some other gist code we have.
Sorry, I’m now sending you a how to setup. (edited) 

Manikandan [11:44 PM]
https://gist.github.com/itsderek23/d9435b21c9a44cd9629e93c4e8c2750e is what I could find in the documentation.

Hiro [11:46 PM]
Sorry for the for the confusion, that is for elixir app. We haven’t mentioned graphql for ruby app in our doc at the moment.

Manikandan [11:47 PM]
Ah, this is where I got confused.

Hiro [11:50 PM]
It’s actually quite simple. You just need to add something like following code in your graphql endpoint.  What it does is we are overwriting the transaction name dynamically based on your query.
```scout_transaction_name = "Graphql/" + [query.operation_name, field_name].compact.join(" ")

ScoutApm::Transaction.rename("posts/foobar")```  
(edited)
This will give you names like “GraphqlController#profile” and “GraphqlController#delete user” in Scout view.
`[query.operation_name, field_name].compact.join(" ")`
This part is an example from us, so please change based on how you would like to rename your transaction :slightly_smiling_face:
